#include <STDInclude.hpp>
#include "D3D11Utils.hpp"

void D3D11::UnpackD3DCOLOR(D3DCOLOR D3D9Color, FLOAT* D3D11Color)
{

}

size_t D3D11::GetFormatSize(DXGI_FORMAT Format)
{
	switch (Format) {
	case DXGI_FORMAT_R32G32B32A32_FLOAT:
		return 16;
	case DXGI_FORMAT_R16G16B16A16_UNORM:
	case DXGI_FORMAT_R16G16B16A16_SNORM:
	case DXGI_FORMAT_R16G16B16A16_FLOAT:
	case DXGI_FORMAT_R32G32_FLOAT:
		return 8;
	case DXGI_FORMAT_B8G8R8A8_TYPELESS:
	case DXGI_FORMAT_R8G8B8A8_TYPELESS:
	case DXGI_FORMAT_R24G8_TYPELESS:
	case DXGI_FORMAT_B8G8R8A8_UNORM:
	case DXGI_FORMAT_B5G5R5A1_UNORM:
	case DXGI_FORMAT_R10G10B10A2_UNORM:
	case DXGI_FORMAT_R8G8B8A8_UNORM:
	case DXGI_FORMAT_R8G8B8A8_SNORM:
	case DXGI_FORMAT_R16G16_UNORM:
	case DXGI_FORMAT_R16G16_SNORM:
	case DXGI_FORMAT_R16G16_FLOAT:
	case DXGI_FORMAT_G8R8_G8B8_UNORM:
	case DXGI_FORMAT_R8G8_B8G8_UNORM:
	case DXGI_FORMAT_R32_UINT:
	case DXGI_FORMAT_R32_FLOAT:
	case DXGI_FORMAT_D32_FLOAT:
	case DXGI_FORMAT_D24_UNORM_S8_UINT:
	case DXGI_FORMAT_R24_UNORM_X8_TYPELESS:
		return 4;
	case DXGI_FORMAT_B5G6R5_UNORM:
	case DXGI_FORMAT_R8G8_UNORM:
	case DXGI_FORMAT_R8G8_SNORM:
	case DXGI_FORMAT_R16_UNORM:
	case DXGI_FORMAT_R16_UINT:
	case DXGI_FORMAT_R16_FLOAT:
	case DXGI_FORMAT_D16_UNORM:
		return 2;
	case DXGI_FORMAT_A8_UNORM:
	case DXGI_FORMAT_R8_UNORM:
		return 1;
	case DXGI_FORMAT_BC1_UNORM:
	case DXGI_FORMAT_BC1_TYPELESS:
		return 8; // per 4x4 pixel blocks
	case DXGI_FORMAT_BC2_UNORM:
	case DXGI_FORMAT_BC3_UNORM:
	case DXGI_FORMAT_BC2_TYPELESS:
	case DXGI_FORMAT_BC3_TYPELESS:
		return 16; // per 4x4 pixel blocks
	case DXGI_FORMAT_UNKNOWN:
	default:
		NOT_IMPLEMENTED;
		return 0;
	}
}

size_t D3D11::GetBlockSize(DXGI_FORMAT Format) {
	switch (Format) {
	case DXGI_FORMAT_BC1_UNORM:
	case DXGI_FORMAT_BC2_UNORM:
	case DXGI_FORMAT_BC3_UNORM:
	case DXGI_FORMAT_BC1_TYPELESS:
	case DXGI_FORMAT_BC2_TYPELESS:
	case DXGI_FORMAT_BC3_TYPELESS:
		return 4; // 4x4 pixel blocks
	default:
		return 1;
	}
}

DXGI_FORMAT D3D11::D3DFORMAT_to_DXGI_FORMAT(D3DFORMAT Format)
{
	switch (Format) {
	case D3DFMT_UNKNOWN: return DXGI_FORMAT_UNKNOWN;
		//case D3DFMT_R8G8B8: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_A8R8G8B8: return DXGI_FORMAT_B8G8R8A8_UNORM;
	case D3DFMT_X8R8G8B8: return DXGI_FORMAT_B8G8R8A8_UNORM; // We add a A8 otherwise it cause issue with swapchain and adapter creation
	case D3DFMT_R5G6B5: return DXGI_FORMAT_B5G6R5_UNORM;
		//case D3DFMT_X1R5G5B5: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_A1R5G5B5: return DXGI_FORMAT_B5G5R5A1_UNORM;
		//case D3DFMT_A4R4G4B4: return DXGI_FORMAT_UNKNOWN;
		//case D3DFMT_R3G3B2: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_A8: return DXGI_FORMAT_A8_UNORM;
		//case D3DFMT_A8R3G3B2: return DXGI_FORMAT_UNKNOWN;
		//case D3DFMT_X4R4G4B4: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_A2B10G10R10: return DXGI_FORMAT_R10G10B10A2_UNORM;
	case D3DFMT_A8B8G8R8: return DXGI_FORMAT_R8G8B8A8_UNORM;
		//case D3DFMT_X8B8G8R8: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_G16R16: return DXGI_FORMAT_R16G16_UNORM;
		//case D3DFMT_A2R10G10B10: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_A16B16G16R16: return DXGI_FORMAT_R16G16B16A16_UNORM;
		//case D3DFMT_A8P8: return DXGI_FORMAT_UNKNOWN;
		//case D3DFMT_P8: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_L8: return DXGI_FORMAT_R8_UNORM;	// need .rrrr swizzle
	case D3DFMT_A8L8: return DXGI_FORMAT_R8G8_UNORM;// need .rrrg swizzle
		//case D3DFMT_A4L4: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_V8U8: return DXGI_FORMAT_R8G8_SNORM;
		//case D3DFMT_L6V5U5: return DXGI_FORMAT_UNKNOWN;
		//case D3DFMT_X8L8V8U8: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_Q8W8V8U8: return DXGI_FORMAT_R8G8B8A8_SNORM;
	case D3DFMT_V16U16: return DXGI_FORMAT_R16G16_SNORM;
		//case D3DFMT_A2W10V10U10: return DXGI_FORMAT_UNKNOWN;
		//case D3DFMT_UYVY: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_R8G8_B8G8: return DXGI_FORMAT_G8R8_G8B8_UNORM; // data is scaled up by 255.0f in dx9
		//case D3DFMT_YUY2: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_G8R8_G8B8: return DXGI_FORMAT_R8G8_B8G8_UNORM; // data is scaled up by 255.0f in dx9
	case D3DFMT_DXT1: return DXGI_FORMAT_BC1_UNORM;
	case D3DFMT_DXT2: return DXGI_FORMAT_BC2_UNORM;
	case D3DFMT_DXT3: return DXGI_FORMAT_BC2_UNORM;
	case D3DFMT_DXT4: return DXGI_FORMAT_BC3_UNORM;
	case D3DFMT_DXT5: return DXGI_FORMAT_BC3_UNORM;
	case D3DFMT_D16: return DXGI_FORMAT_D16_UNORM;
	case D3DFMT_D16_LOCKABLE: return DXGI_FORMAT_D16_UNORM;
	case D3DFMT_D32: return DXGI_FORMAT_D32_FLOAT;
		//case D3DFMT_D15S1: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_D24S8: return DXGI_FORMAT_D24_UNORM_S8_UINT;
	case D3DFMT_D24X8: return DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
	case D3DFMT_D24FS8: return DXGI_FORMAT_D24_UNORM_S8_UINT; // ???
		//case D3DFMT_D24X4S4: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_D32F_LOCKABLE: return DXGI_FORMAT_D32_FLOAT;
	case D3DFMT_L16: return DXGI_FORMAT_R16_UNORM;		// need .rrrr swizzle
	case D3DFMT_INDEX16: return DXGI_FORMAT_R16_UINT;
	case D3DFMT_INDEX32: return DXGI_FORMAT_R32_UINT;
	case D3DFMT_Q16W16V16U16: return DXGI_FORMAT_R16G16B16A16_SNORM;
		//case D3DFMT_MULTI2_ARGB8: return DXGI_FORMAT_UNKNOWN;
	case D3DFMT_R16F: return DXGI_FORMAT_R16_FLOAT;
	case D3DFMT_G16R16F: return DXGI_FORMAT_R16G16_FLOAT;
	case D3DFMT_A16B16G16R16F: return DXGI_FORMAT_R16G16B16A16_FLOAT;
	case D3DFMT_R32F: return DXGI_FORMAT_R32_FLOAT;
	case D3DFMT_G32R32F: return DXGI_FORMAT_R32G32_FLOAT;
	case D3DFMT_A32B32G32R32F: return DXGI_FORMAT_R32G32B32A32_FLOAT;
		//case D3DFMT_CxV8U8: return DXGI_FORMAT_UNKNOWN;
	default:
		return DXGI_FORMAT_UNKNOWN;
		//NOT_IMPLEMENTED;
	}
}

DXGI_FORMAT D3D11::GetSRGBFormat(DXGI_FORMAT Format)
{
	switch (Format) {
	case DXGI_FORMAT_B8G8R8A8_UNORM: return DXGI_FORMAT_B8G8R8A8_UNORM_SRGB;
	case DXGI_FORMAT_R8G8B8A8_UNORM: return DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
	case DXGI_FORMAT_BC1_UNORM: return DXGI_FORMAT_BC1_UNORM_SRGB;
	case DXGI_FORMAT_BC2_UNORM: return DXGI_FORMAT_BC2_UNORM_SRGB;
	case DXGI_FORMAT_BC3_UNORM: return DXGI_FORMAT_BC3_UNORM_SRGB;
	default: return DXGI_FORMAT_UNKNOWN;
	}
}

DXGI_FORMAT D3D11::GetTypelessFormat(DXGI_FORMAT Format)
{
	switch (Format) {
	case DXGI_FORMAT_B8G8R8A8_UNORM: return DXGI_FORMAT_B8G8R8A8_TYPELESS;
	case DXGI_FORMAT_R8G8B8A8_UNORM: return DXGI_FORMAT_R8G8B8A8_TYPELESS;
	case DXGI_FORMAT_BC1_UNORM: return DXGI_FORMAT_BC1_TYPELESS;
	case DXGI_FORMAT_BC2_UNORM: return DXGI_FORMAT_BC2_TYPELESS;
	case DXGI_FORMAT_BC3_UNORM: return DXGI_FORMAT_BC3_TYPELESS;
	case DXGI_FORMAT_D24_UNORM_S8_UINT: return DXGI_FORMAT_R24G8_TYPELESS;
	default: return DXGI_FORMAT_UNKNOWN;
	}
}

LPCSTR D3D11::D3D9UsageToSemantic(BYTE Usage)
{
	switch (Usage) {
	case D3DDECLUSAGE_POSITION: return "POSITION";
	case D3DDECLUSAGE_BLENDWEIGHT: return "BLENDWEIGHT";
	case D3DDECLUSAGE_BLENDINDICES: return "BLENDINDICES";
	case D3DDECLUSAGE_NORMAL: return "NORMAL";
	case D3DDECLUSAGE_PSIZE: return "PSIZE";
	case D3DDECLUSAGE_TEXCOORD: return "TEXCOORD";
	case D3DDECLUSAGE_TANGENT: return "TANGENT";
	case D3DDECLUSAGE_BINORMAL: return "BINORMAL";
	case D3DDECLUSAGE_TESSFACTOR: return "TESSFACTOR";
	case D3DDECLUSAGE_POSITIONT: return "POSITIONT";
	case D3DDECLUSAGE_COLOR: return "COLOR";
	case D3DDECLUSAGE_FOG: return "FOG";
	case D3DDECLUSAGE_DEPTH: return "DEPTH";
	case D3DDECLUSAGE_SAMPLE:
	default:
		NOT_IMPLEMENTED;
		return "TEXCOORD";
	}
}

DXGI_FORMAT D3D11::D3D9DeclTypeToDXGI_Format(BYTE Usage)
{
	switch (Usage) {
	case D3DDECLTYPE_FLOAT1:    return DXGI_FORMAT_R32_FLOAT;			// 1D float expanded to (value, 0., 0., 1.)
	case D3DDECLTYPE_FLOAT2:	return DXGI_FORMAT_R32G32_FLOAT;		// 2D float expanded to (value, value, 0., 1.)
	case D3DDECLTYPE_FLOAT3:	return DXGI_FORMAT_R32G32B32_FLOAT;		// 3D float expanded to (value, value, value, 1.)
	case D3DDECLTYPE_FLOAT4:	return DXGI_FORMAT_R32G32B32A32_FLOAT;	// 4D float
	case D3DDECLTYPE_D3DCOLOR:	return DXGI_FORMAT_B8G8R8A8_UNORM;		// 4D packed unsigned bytes mapped to 0. to 1. range
		// Input is in D3DCOLOR format (ARGB) expanded to (R, G, B, A)
	case D3DDECLTYPE_UBYTE4:    return DXGI_FORMAT_R8G8B8A8_UINT;		// 4D unsigned byte
	case D3DDECLTYPE_SHORT2:    return DXGI_FORMAT_R16G16_SINT;			// 2D signed short expanded to (value, value, 0., 1.)
	case D3DDECLTYPE_SHORT4:    return DXGI_FORMAT_R16G16B16A16_SINT;	// 4D signed short

		// The following types are valid only with vertex shaders >= 2.0
	case D3DDECLTYPE_UBYTE4N:	return DXGI_FORMAT_R8G8B8A8_UNORM;		// Each of 4 bytes is normalized by dividing to 255.0
	case D3DDECLTYPE_SHORT2N:	return DXGI_FORMAT_R16G16_SNORM;		// 2D signed short normalized (v[0]/32767.0,v[1]/32767.0,0,1)
	case D3DDECLTYPE_SHORT4N:	return DXGI_FORMAT_R16G16B16A16_SNORM;  // 4D signed short normalized (v[0]/32767.0,v[1]/32767.0,v[2]/32767.0,v[3]/32767.0)
	case D3DDECLTYPE_USHORT2N:	return DXGI_FORMAT_R16G16_UNORM;		// 2D unsigned short normalized (v[0]/65535.0,v[1]/65535.0,0,1)
	case D3DDECLTYPE_USHORT4N:	return DXGI_FORMAT_R16G16B16A16_UNORM;  // 4D unsigned short normalized (v[0]/65535.0,v[1]/65535.0,v[2]/65535.0,v[3]/65535.0)
	case D3DDECLTYPE_UDEC3:		return DXGI_FORMAT_R10G10B10A2_UINT;	// 3D unsigned 10 10 10 format expanded to (value, value, value, 1)
		//case D3DDECLTYPE_DEC3N:		return DXGI_FORMAT_R10G10B10A2_UNORM;	// 3D signed 10 10 10 format normalized and expanded to (v[0]/511.0, v[1]/511.0, v[2]/511.0, 1)
	case D3DDECLTYPE_FLOAT16_2:	return DXGI_FORMAT_R16G16_FLOAT;		// Two 16-bit floating point values, expanded to (value, value, 0, 1)
	case D3DDECLTYPE_FLOAT16_4: return DXGI_FORMAT_R16G16B16A16_FLOAT;  // Four 16-bit floating point values
	case D3DDECLTYPE_UNUSED:	return DXGI_FORMAT_UNKNOWN;				// When the type field in a decl is unused.
	default:
		NOT_IMPLEMENTED;
		return DXGI_FORMAT_UNKNOWN;
	}
}

D3D11_TEXTURE_ADDRESS_MODE D3D11::D3DTEXTUREADDRESSToD3D11_TEXTURE_ADDRESS_MODE(D3DTEXTUREADDRESS Mode)
{
	switch (Mode) {
		case D3DTADDRESS_WRAP: return D3D11_TEXTURE_ADDRESS_WRAP;
		case D3DTADDRESS_MIRROR: return D3D11_TEXTURE_ADDRESS_MIRROR;
		case D3DTADDRESS_CLAMP: return D3D11_TEXTURE_ADDRESS_CLAMP;
		case D3DTADDRESS_BORDER: return D3D11_TEXTURE_ADDRESS_BORDER;
		case D3DTADDRESS_MIRRORONCE: return D3D11_TEXTURE_ADDRESS_MIRROR_ONCE;
		default:
			NOT_IMPLEMENTED;
			return D3D11_TEXTURE_ADDRESS_WRAP;
	}
}

D3D11_STENCIL_OP D3D11::D3DSTENCILOPToD3D11_STENCIL_OP(D3DSTENCILOP Op)
{
	switch (Op) {
	case D3DSTENCILOP_KEEP: return D3D11_STENCIL_OP_KEEP;
	case D3DSTENCILOP_ZERO: return D3D11_STENCIL_OP_ZERO;
	case D3DSTENCILOP_REPLACE: return D3D11_STENCIL_OP_REPLACE;
	case D3DSTENCILOP_INCRSAT: return D3D11_STENCIL_OP_INCR_SAT;
	case D3DSTENCILOP_DECRSAT: return D3D11_STENCIL_OP_DECR_SAT;
	case D3DSTENCILOP_INVERT: return D3D11_STENCIL_OP_INVERT;
	case D3DSTENCILOP_INCR: return D3D11_STENCIL_OP_INCR;
	case D3DSTENCILOP_DECR: return D3D11_STENCIL_OP_DECR;
	default:
		NOT_IMPLEMENTED;
		return D3D11_STENCIL_OP_KEEP;
	}
}

D3D11_COMPARISON_FUNC D3D11::D3DCMPFUNCToD3D11_COMPARISON_FUNC(D3DCMPFUNC Func)
{
	switch (Func) {
	case D3DCMP_NEVER: return D3D11_COMPARISON_NEVER;
	case D3DCMP_LESS: return D3D11_COMPARISON_LESS;
	case D3DCMP_EQUAL: return D3D11_COMPARISON_EQUAL;
	case D3DCMP_LESSEQUAL: return D3D11_COMPARISON_LESS_EQUAL;
	case D3DCMP_GREATER: return D3D11_COMPARISON_GREATER;
	case D3DCMP_NOTEQUAL: return D3D11_COMPARISON_NOT_EQUAL;
	case D3DCMP_GREATEREQUAL: return D3D11_COMPARISON_GREATER_EQUAL;
	case D3DCMP_ALWAYS: return D3D11_COMPARISON_ALWAYS;
	default:
		NOT_IMPLEMENTED;
		return D3D11_COMPARISON_NEVER;
	}
}

D3D11_BLEND D3D11::D3DBLENDToD3D11_BLEND(D3DBLEND Blend, bool alpha)
{
	switch (Blend) {
	case D3DBLEND_ZERO: return D3D11_BLEND_ZERO;
	case D3DBLEND_ONE: return D3D11_BLEND_ONE;
	case D3DBLEND_SRCCOLOR: return D3D11_BLEND_SRC_COLOR;
	case D3DBLEND_INVSRCCOLOR: return D3D11_BLEND_INV_SRC_COLOR;
	case D3DBLEND_SRCALPHA: return D3D11_BLEND_SRC_ALPHA;
	case D3DBLEND_INVSRCALPHA: return D3D11_BLEND_INV_SRC_ALPHA;
	case D3DBLEND_DESTALPHA: return D3D11_BLEND_DEST_ALPHA;
	case D3DBLEND_INVDESTALPHA: return D3D11_BLEND_INV_DEST_ALPHA;
	case D3DBLEND_DESTCOLOR: return alpha ? D3D11_BLEND_DEST_ALPHA : D3D11_BLEND_DEST_COLOR;
	case D3DBLEND_INVDESTCOLOR: return alpha ? D3D11_BLEND_INV_DEST_ALPHA : D3D11_BLEND_INV_DEST_COLOR;
	case D3DBLEND_SRCALPHASAT: return D3D11_BLEND_SRC_ALPHA_SAT;
	case D3DBLEND_BLENDFACTOR: return D3D11_BLEND_BLEND_FACTOR;
	case D3DBLEND_INVBLENDFACTOR: return D3D11_BLEND_INV_BLEND_FACTOR;
	case D3DBLEND_BOTHSRCALPHA:
	case D3DBLEND_BOTHINVSRCALPHA:
	default:
		NOT_IMPLEMENTED;
		return D3D11_BLEND_ZERO;
	}
}

D3D11_BLEND_OP D3D11::D3DBLENDOPToD3D11_BLEND_OP(D3DBLENDOP Op)
{
	switch (Op) {
	case D3DBLENDOP_ADD: return D3D11_BLEND_OP_ADD;
	case D3DBLENDOP_SUBTRACT: return D3D11_BLEND_OP_SUBTRACT;
	case D3DBLENDOP_REVSUBTRACT: return D3D11_BLEND_OP_REV_SUBTRACT;
	case D3DBLENDOP_MIN: return D3D11_BLEND_OP_MIN;
	case D3DBLENDOP_MAX: return D3D11_BLEND_OP_MAX;
	default:
		NOT_IMPLEMENTED;
		return D3D11_BLEND_OP_ADD;
	}
}

D3D11_FILL_MODE D3D11::D3DFILLMODEToD3D11_FILL_MODE(D3DFILLMODE Mode)
{
	switch (Mode) {
	case D3DFILL_WIREFRAME: return D3D11_FILL_WIREFRAME;
	case D3DFILL_SOLID: return D3D11_FILL_SOLID;
	default:
		NOT_IMPLEMENTED;
		return D3D11_FILL_SOLID;
	}
}

D3D11_CULL_MODE D3D11::D3DCULLToD3D11_CULL_MODE(D3DCULL Mode)
{
	switch (Mode) {
	case D3DCULL_NONE: return D3D11_CULL_NONE;
	case D3DCULL_CW: return D3D11_CULL_FRONT;
	case D3DCULL_CCW: return D3D11_CULL_BACK;
	default:
		NOT_IMPLEMENTED;
		return D3D11_CULL_BACK;
	}
}
