name: Feature Request
description: Suggest a new feature for IW4x
body:
  - type: textarea
    id: problem-description
    attributes:
      label: What problem does this solve?
      description: A clear and concise description of the problem this new feature is meant to solve.
    validations:
      required: true

  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. "I'm always frustrated when [...]"
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical considerations
      description: If you have technical knowledge, describe how you envision this being implemented.
    validations:
      required: false

  - type: checkboxes
    id: compatibility-impact
    attributes:
      label: Compatibility impact
      options:
        - label: This change would be backward compatible
        - label: This change might break compatibility with existing servers/mods
        - label: Unsure about compatibility impact

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: existing-workarounds
    attributes:
      label: Existing workarounds
      description: Are there any current workarounds for this issue?
    validations:
      required: false

  - type: textarea
    id: supporting-materials
    attributes:
      label: Supporting materials
      description: |
        - Screenshots, videos, or mockups that illustrate the feature
        - Links to relevant documentation
        - Any other context that would help explain the feature
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have limited this request to a single feature
          required: true
        - label: I have provided clear use cases for this feature
          required: true
        - label: I have considered the implementation complexity and compatibility impact
          required: true
