name: Release

on:
  push:
    tags:
      - r[0-9]+

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-tag-is-correct:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify the tag matches the commit count
        run: |
          EXPECTED_TAG="r$(git rev-list --count HEAD)"
          ACTUAL_TAG="${{ github.ref_name }}"
          ([[ "$EXPECTED_TAG" == "$ACTUAL_TAG" ]] && echo "Tag $ACTUAL_TAG is correct!") || (echo "Tag is wrong! Expected $EXPECTED_TAG." && exit 1)

  create-release:
    needs:
      - verify-tag-is-correct
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          allowUpdates: true
          omitBodyDuringUpdate: true

  build-release:
    needs:
      - verify-tag-is-correct
    runs-on: windows-2022
    env:
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_RELEASE: iw4x@${{ github.ref_name }}
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Generate project files
        run: tools/premake5 vs2022 --sentry-dsn=${{ secrets.SENTRY_DSN }}

      - name: Build release binaries
        run: msbuild /m /v:minimal /p:Configuration=Release /p:Platform=Win32 build/iw4x.sln

      - name: Upload debug symbols to Sentry
        if: env.SENTRY_AUTH_TOKEN != ''
        run: |
          npm install -g @sentry/cli
          sentry-cli releases new "$env:SENTRY_RELEASE"
          sentry-cli debug-files upload --include-sources build/bin/Win32/Release
          sentry-cli releases finalize "$env:SENTRY_RELEASE"

      - name: Upload release binaries
        uses: actions/upload-artifact@v4
        with:
          name: iw4x-release
          path: |
            build/bin/Win32/Release/iw4x.dll
            build/bin/Win32/Release/iw4x.pdb
            build/bin/Win32/Release/sentry-crash.exe
            build/bin/Win32/Release/sentry-crash.pdb
            build/bin/Win32/Release/sentry-wer.dll
            build/bin/Win32/Release/sentry-wer.pdb

  release:
    needs:
      - create-release
      - build-release
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: iw4x-release
          path: iw4x-release
      - name: Prepare release tool
        run: |
          wget -O release-tool.tar.gz https://github.com/iw4x/launcher/releases/latest/download/release-tool-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf release-tool.tar.gz
          chmod +x release-tool
      - name: Create release information
        run: |
          mkdir -p ./launcher-files
          mv -v iw4x-release/iw4x.dll launcher-files/iw4x.dll
          mv -v iw4x-release/sentry-crash.exe launcher-files/sentry-crash.exe
          mv -v iw4x-release/sentry-wer.dll launcher-files/sentry-wer.dll
          ./release-tool ./launcher-files
      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "launcher-files/*,iw4x-release/*"
          artifactErrorsFailBuild: true
          allowUpdates: true
          draft: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
